language: python
python:
#  - "3.5"
  - "3.6"
env:
  matrix:
  - NETWORKX_VERSION=2.0
#  - NETWORKX_VERSION=2.1
#  - NETWORKX_VERSION=2.2

install:
- pip install -q networkx==$NETWORKX_VERSION
- pip install -q -r requirements.txt
- pip install sphinx sphinx sphinxcontrib-napoleon sphinx_rtd_theme
script:
#- python3 -m pytest -v
- cd docs
- make html
- touch build/.nojekyll
- cd ..
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/build/html
  on:
    branch: dev
notifications:
  email: false
