language: python
python:
    #  - "3.2" # scipy requires python >= 3.4
    #  - "3.3"
    #  - "3.4" # networkx2.0 requires python >= 3.6
  # - "3.5"
  - "3.6"
env:
  # - NETWORKX_VERSION=1.9
  - NETWORKX_VERSION=2.0
# command to install dependencies
install:
  - pip install -q networkx==$NETWORKX_VERSION
  - pip install -q -r requirements.txt
  # install packages to track test coverage
  - pip install -q coverage pytest-cov coverage-badge
# command to run tests
script:
# This runs test discovery on all modules with names ending '_test'
  - py.test --cov=BrainNetworksInPython
# Report on coverage
  - coverage report -m
# Save coverage badge
  - coverage-badge -o coverage.svg
# Silence email notifications
notifications:
  email: false
